name: Create Kernel Release

on:
  workflow_run:
    workflows: ["Patch_Kernel_KPM"]
    types:
      - completed

jobs:
  check_trigger:
    name: Verify Patch Result
    runs-on: ubuntu-latest
    steps:
      - name: Check if patch workflow was successful
        if: github.event.workflow_run.conclusion != 'success'
        run: |
          echo "Triggering patch workflow was not successful (conclusion: ${{ github.event.workflow_run.conclusion }}). Stopping."
          exit 1
  release:
    name: Create GitHub Release
    needs: check_trigger
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
    env:
      TZ: Asia/Kolkata
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Send Start Notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID_PERSONAL }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: markdown
          message: |
            *🚀 Release Process Started*
            ------------------------------------
            This is the final step: creating the GitHub Release.
            [View Release Run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
            
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate IST Release Tag
        id: generate_tag
        run: |
          TAG="oneplus_nord_3-$(date +'%Y-%m-%d_%H-%M')-IST"
          echo "Generated Tag: $TAG"
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Download Patched Artifacts
        run: |
          echo "Downloading artifacts from Run ID ${{ github.event.workflow_run.id }}..."
          gh run download ${{ github.event.workflow_run.id }} --dir ./downloaded-artifacts --repo ${{ github.repository }}

      - name: Display Downloaded Artifact Structure
        run: ls -R ./downloaded-artifacts

      - name: Zip Each Artifact Individually
        run: |
          mkdir ./final-zips
          for dir in ./downloaded-artifacts/*; do
            if [ -d "$dir" ]; then
              ARTIFACT_NAME=$(basename "$dir")
              echo "Zipping artifact: $ARTIFACT_NAME"
              (cd "$dir" && zip -r9 "$GITHUB_WORKSPACE/final-zips/${ARTIFACT_NAME}.zip" .)
            fi
          done

      - name: Create GitHub Release and Upload Zips
        id: create_release
        env:
          RELEASE_NOTES: |
            ### SukiSU Ultra Kernel
            Flash on AOSP.
        run: |
          TAG="oneplus_nord_3-$(date +'%Y-%m-%d_%H-%M')-IST"
          echo "release_tag=$TAG" >> $GITHUB_OUTPUT
          gh release create "$TAG" \
            --title "Kernel Release - $(date +'%d %B %Y')" \
            --notes "$RELEASE_NOTES" \
            ./final-zips/*.zip
            
  notify_result:
    name: Notify Final Release Status
    needs: release
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Send Final Release Notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ needs.release.result == 'success' && secrets.TELEGRAM_CHAT_ID_PRIVATE2 || secrets.TELEGRAM_CHAT_ID_PERSONAL }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: markdown
          message: |
            ${{ needs.release.result == 'success' && format('🎉 *New Kernel Release!*
            ------------------------------------
            A new kernel has been successfully built, patched, and released.

            *Release Tag:* `{0}`
            ------------------------------------
            [⬇️ Download from GitHub Releases](https://github.com/{1}/releases/tag/{0})', needs.release.outputs.release_tag, github.repository) || '' }}

            ${{ needs.release.result == 'failure' && format('❌ *Release Failed!*
            ------------------------------------
            The final step of creating the GitHub Release failed. Check logs for details.
            [View Logs](https://github.com/{0}/actions/runs/{1})', github.repository, github.run_id) || '' }}

            ${{ needs.release.result == 'cancelled' && format('🚫 *Release Cancelled*
            ------------------------------------
            The final release process was cancelled.
            [View Run](https://github.com/{0}/actions/runs/{1})', github.repository, github.run_id) || '' }}
