name: Send Build Notifications

on:
  workflow_run:
    workflows: ["Build OnePlus Nord 3 Stock"] # The 'name:' from your build file
    types:
      - completed # This trigger runs for success, failure, and cancellations

jobs:
  notify:
    name: Send Notification 🔔
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Workflow Inputs
        id: get_inputs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUN_ID: ${{ github.event.workflow_run.id }}
        run: |
          sudo apt-get update && sudo apt-get install -y jq
          API_URL="https://api.github.com/repos/${{ github.repository }}/actions/runs/$RUN_ID"
          response=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" "$API_URL")
          file=$(echo "$response" | jq -r '.triggering_actor.login + "/" + .display_title' | sed 's/For //')
          echo "build_info=$file" >> $GITHUB_OUTPUT

      - name: Send Result Notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ github.event.workflow_run.conclusion == 'success' && secrets.TELEGRAM_CHAT_ID_PRIVATE2 || secrets.TELEGRAM_CHAT_ID_PERSONAL }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: markdown
          message: |
            ${{ github.event.workflow_run.conclusion == 'success' && format('✅ *Build Successful*
            ------------------------------------
            *Configuration:* `{0}`
            *Commit:* `{1}`
            ------------------------------------
            The artifact is ready for the patching workflow.', steps.get_inputs.outputs.build_info, github.event.workflow_run.head_sha) || '' }}

            ${{ github.event.workflow_run.conclusion == 'failure' && format('❌ *Build Failed*
            ------------------------------------
            *Configuration:* `{0}`
            *Commit:* `{1}`
            ------------------------------------
            Please check the logs for details.', steps.get_inputs.outputs.build_info, github.event.workflow_run.head_sha) || '' }}
            
            ${{ github.event.workflow_run.conclusion == 'cancelled' && format('🚫 *Build Cancelled*
            ------------------------------------
            *Configuration:* `{0}`
            *Commit:* `{1}`
            ------------------------------------
            The build was cancelled by a user.', steps.get_inputs.outputs.build_info, github.event.workflow_run.head_sha) || '' }}

            [View Completed Run](https://github.com/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }})
